services:
  web:
    build: .
    image: rada-img:local
    ports:
      - "8000:8000"
    command: ["/bin/bash", "run_django.sh"]
    depends_on:
      - db
    volumes:
      - .:/app/final/rada
      - /var/www/rada/staticfiles:/app/final/rada/static
    environment:
      - CELERY_BROKER_URL='redis://redis:6379/0'
      - CELERY_RESULT_BACKEND='redis://redis:6379/0'
      - POSTGRES_HOST=db
      - EMAIL_PASS=dpsiyvecvuecxifq
    env_file:
      - ./new.env
    restart: unless-stopped
  
  db:
    image: postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      # DB_NAME: "radadb"
      # DB_PASS: "password"
      # DB_USER: "ronny"
      - POSTGRES_USER=ronny
      - POSTGRES_PASS=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=radadb
      - POSTGRES_HOST=db
    volumes:
      - db-data:/var/lib/postgresql/db
    restart: unless-stopped

  celery:
    # build: .
    image: rada-img:local
    # command: ./wait-for-migrations.sh celery -A core.mycelery worker -l info --pool=solo
    command: celery -A core.mycelery worker -l info --pool=solo
    volumes:
      - .:/app/final/rada
    depends_on:
      - web
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_USER=ronny
      - POSTGRES_PASS=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=radadb
      - POSTGRES_HOST=db
    restart: unless-stopped
  
  celery_beat:
    # build: .
    image: rada-img:local
    # command: ./wait-for-migrations.sh celery -A core.mycelery beat -l info
    command: celery -A core.mycelery beat -l info
    depends_on:
      - redis
      - web
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - POSTGRES_USER=ronny
      - POSTGRES_PASS=password
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=radadb
      - POSTGRES_HOST=db
    restart: unless-stopped


  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db-data:
  staticfiles_volume:
